### ISSUE TITLE
Есть ли вариант подключения через composer?

### ISSUE THREAD

**Issue by dorantor** [smi2/phpMigrationsClickhouse#1]
Здравствуйте, 

Очень хочется держать все зависимости в одном месте и в одном виде(composer.json), т.к. это уменьшает вероятность обновить одно, а про другое - забыть.

**Comment by isublimity** [comment]
Этот проект depricated - т/к в самом CH появился DDL ... 
Поэтому изначально его- я не поддерживал сильно 
Хотя в проде именно он у нас ) т/к DDL только только нормально заработал в CH )

**Comment by dorantor** [comment]
Вы бы уж написали тогда об этом в ридми :)
